CREATE TABLE owners (id TEXT PRIMARY KEY NOT NULL, created_at INTEGER NOT NULL);
INSERT INTO owners SELECT id, created_at FROM sessions;
CREATE TABLE users (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL REFERENCES owners(id), email TEXT NOT NULL, name TEXT NOT NULL, password_hash TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE UNIQUE INDEX users_owner_id_unique ON users(owner_id);
CREATE UNIQUE INDEX users_email_unique ON users(email);
ALTER TABLE sessions ADD COLUMN owner_id TEXT REFERENCES owners(id);
ALTER TABLE sessions ADD COLUMN user_id TEXT REFERENCES users(id);
ALTER TABLE sessions ADD COLUMN expires_at INTEGER;
UPDATE sessions SET owner_id=id, expires_at=created_at+2592000000;
CREATE INDEX idx_sessions_owner ON sessions(owner_id);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE TABLE projects_new (id TEXT PRIMARY KEY NOT NULL, owner TEXT NOT NULL REFERENCES owners(id), title TEXT NOT NULL, current_version INTEGER NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT '{}', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
INSERT INTO projects_new SELECT * FROM projects;
CREATE TABLE versions_new (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL REFERENCES projects_new(id) ON DELETE CASCADE, number INTEGER NOT NULL, prompt TEXT NOT NULL, summary TEXT NOT NULL, code TEXT NOT NULL, mode TEXT NOT NULL, created_at INTEGER NOT NULL, files TEXT NOT NULL DEFAULT '{}', trace TEXT NOT NULL DEFAULT '[]');
INSERT INTO versions_new (id,project_id,number,prompt,summary,code,mode,created_at,files,trace) SELECT id,project_id,number,prompt,summary,code,mode,created_at,files,trace FROM versions;
DROP TABLE versions;
DROP TABLE projects;
ALTER TABLE projects_new RENAME TO projects;
ALTER TABLE versions_new RENAME TO versions;
CREATE INDEX idx_projects_owner_updated ON projects(owner,updated_at);
CREATE UNIQUE INDEX idx_versions_project_number ON versions(project_id,number);
CREATE TABLE auth_attempts (id TEXT PRIMARY KEY NOT NULL, hits INTEGER NOT NULL, expires_at INTEGER NOT NULL);
