'use client';
import { useEffect,useState } from 'react';
import { BookOpen, Check, Loader2, PlugZap, RefreshCw, Wrench } from 'lucide-react';
import { ConnectionsPanel } from './connections-panel';
import type { AgentCatalog } from '@/lib/agent-types';
export function ExtensionsPanel(){
  const [catalog,setCatalog]=useState<AgentCatalog|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[updating,setUpdating]=useState('');
  async function loadCatalog(){try{const response=await fetch('/api/harness');const data=await response.json() as AgentCatalog & {error?:string};if(!response.ok)throw new Error(data.error||'无法加载工具');setCatalog(data);}catch(error){setError((error as Error).message);}finally{setLoading(false);}}
  function refresh(){setLoading(true);setError('');return loadCatalog();}
  // Fetch the external MCP catalog on mount; state updates follow the response.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void loadCatalog();},[]);
  async function toggle(id:string,enabled:boolean){setUpdating(id);try{const response=await fetch('/api/harness',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,enabled})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||'更新失败');await refresh();}catch(error){setError((error as Error).message);}finally{setUpdating('');}}
  return <div className="extensions-panel"><ConnectionsPanel/><p className="extensions-intro">Agent 会根据任务自主调用工具。启用的插件提供 MCP 工具和按需加载的 Skill；更改在下一次任务生效。</p><div className="extensions-toolbar"><span><PlugZap size={15}/>{catalog?`${catalog.plugins.filter(p=>p.enabled).length} 个已启用扩展`:'发现工具中…'}</span><button className="secondary-button" onClick={()=>void refresh()} disabled={loading}>{loading?<Loader2 size={14} className="spin"/>:<RefreshCw size={14}/>}刷新</button></div>{error&&<p className="connection-result failure" role="alert">{error}</p>}{!catalog&&loading&&<div className="extensions-loading"><Loader2 className="spin"/>正在连接 MCP 服务并读取 tools/list…</div>}{catalog?.plugins.map(plugin=><div className="extension-card" key={plugin.id}><div className="extension-top"><strong>{plugin.name}</strong><small>{plugin.transport}</small>{plugin.id==='core'?<span className="extension-fixed"><Check size={12}/>内置</span>:<button role="switch" aria-checked={plugin.enabled} aria-label={`${plugin.enabled?'停用':'启用'}${plugin.name}`} className={`extension-toggle ${plugin.enabled?'on':''}`} disabled={!!updating||loading} onClick={()=>void toggle(plugin.id,!plugin.enabled)}><i/></button>}</div><p>{plugin.description}</p>{plugin.error&&<div className="extension-error">{plugin.error}</div>}{plugin.tools.length>0&&<details><summary><Wrench size={13}/>{plugin.tools.length} 个已发现工具</summary><div className="tool-chips">{plugin.tools.map(tool=><code key={tool}>{tool}</code>)}</div></details>}</div>)}<div className="skill-section"><h3><BookOpen size={15}/>可用 Skill <small>{catalog?.skills.length||0}</small></h3>{catalog?.skills.map(skill=><details className="skill-card" key={skill.id}><summary>{skill.name}<small>{skill.plugin}</small></summary><p>{skill.description}</p><code>{skill.id}</code></details>)}</div>{catalog&&<div className="harness-limits"><strong>循环退出条件</strong><p>交付工具检查通过 · 用户停止 · 超时 · 超过调用预算 · 连续无进展</p><span>最多 {catalog.limits.maxIterations} 轮 / {catalog.limits.maxToolCalls} 次调用 / 单轮 {catalog.limits.maxCallsPerTurn??4} 次 / 联网 {catalog.limits.maxResearchCalls??6} 次 / {catalog.limits.timeoutSeconds} 秒 / 截断恢复最多 {catalog.limits.maxOutputRetries??2} 次</span></div>}<p className="extension-guide">本机插件目录在 atmos.config.json 中配置；plugin.json 可声明 stdio / HTTP / SSE MCP 和 SKILL.md。私有配置使用 atmos.local.json。配置完成后刷新即可加载，无需修改 Agent 循环代码。</p></div>;
}
