'use client';
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { BookOpen, Brain, Check, Download, FileText, GitFork, History, Inbox, Loader2, Plus, RefreshCw, Search, Trash2, Upload, X } from 'lucide-react';
import type { Identity } from '@/lib/auth-types';
import { markdownIndex, memoryLinks, resolveMemoryTarget, rankMemories, type MemoryDocument, type MemoryProposal, type MemoryVault } from '@/lib/memory-types';
import { MemoryGraph } from './memory-graph';

type Draft={kind:'doc'|'proposal'|'new';id:string;revision:number;path:string;title:string;content:string;tags:string;enabled:boolean;pinned:boolean};
const date=(n:number)=>new Date(n).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
function docDraft(d:MemoryDocument):Draft{return {...d,kind:'doc',tags:d.tags.join(', ')};}
function proposalDraft(p:MemoryProposal):Draft{return {...p,kind:'proposal',revision:0,path:'',tags:p.tags.join(', '),enabled:true,pinned:false};}
function download(name:string,content:string,type='text/markdown;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function markdownLines(content:string){let code=false;return content.split('\n').map(line=>{if(line.startsWith('```')){code=!code;return {line,code,fence:true};}return {line,code,fence:false};});}
function Markdown({content,documents,open}:{content:string;documents:MemoryDocument[];open:(id:string)=>void}){
  function inline(text:string):ReactNode[]{return text.split(/(\[\[[^\]\n]+\]\])/g).map((part,i)=>{if(!part.startsWith('[[')||!part.endsWith(']]'))return part;const target=part.slice(2,-2),resolved=resolveMemoryTarget(documents,target);return <button type="button" key={i} className={`memory-wikilink ${resolved?'':'unresolved'}`} disabled={!resolved} title={resolved?target:'未找到文档，或名称不唯一'} onClick={()=>resolved&&open(resolved.id)}>{target.split('|')[1]||target.split('|')[0]}</button>;});}
  return <div className="memory-markdown">{markdownLines(content).map(({line,code,fence},i)=>{if(fence)return null;if(code)return <pre key={i}>{line||' '}</pre>;if(line.startsWith('### '))return <h4 key={i}>{inline(line.slice(4))}</h4>;if(line.startsWith('## '))return <h3 key={i}>{inline(line.slice(3))}</h3>;if(line.startsWith('# '))return <h2 key={i}>{inline(line.slice(2))}</h2>;if(/^[-*] /.test(line))return <p className="memory-list-line" key={i}>• {inline(line.slice(2))}</p>;return <p key={i}>{inline(line)||'\u00a0'}</p>;})}</div>;
}
export function MemoryCenter({identity,onClose}:{identity:Identity;onClose:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null),file=useRef<HTMLInputElement>(null),alive=useRef(true);
  const [vault,setVault]=useState<MemoryVault|null>(null),[draft,setDraft]=useState<Draft|null>(null),[tab,setTab]=useState<'docs'|'graph'|'pending'|'history'>('docs'),[query,setQuery]=useState(''),[tag,setTag]=useState(''),[selected,setSelected]=useState(''),[index,setIndex]=useState(false),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
  const [baseline,setBaseline]=useState('');
  const dirty=!!draft&&JSON.stringify(draft)!==baseline;
  async function api(action?:Record<string,unknown>){const response=await fetch('/api/memory',{method:action?'POST':'GET',headers:{'Content-Type':'application/json','X-Atmos-Owner':identity.ownerId},...(action?{body:JSON.stringify(action)}:{})});const result=await response.json() as MemoryVault&{error?:string};if(!response.ok)throw new Error(result.error||'无法读取记忆库');if(!alive.current)throw new Error('身份已切换或窗口已关闭。');return result;}
  useEffect(()=>{alive.current=true;dialog.current?.showModal();void api().then(v=>{setVault(v);const d=docDraft(v.documents[0]);setBaseline(JSON.stringify(d));setDraft(d);setSelected(d.id);}).catch(e=>{if(alive.current)setError(e.message);}).finally(()=>{if(alive.current)setLoading(false);});const retire=()=>{alive.current=false;};window.addEventListener('atmos:retire',retire);return()=>{alive.current=false;window.removeEventListener('atmos:retire',retire);};},[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!dirty)return;const unload=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[dirty]);
  function canLeave(){return !dirty||window.confirm('当前 Markdown 草稿尚未保存，确定放弃这些修改吗？');}
  function close(){if(!busy&&canLeave())onClose();}
  function choose(next:Draft|null){if(!canLeave())return false;setBaseline(JSON.stringify(next));setDraft(next);setIndex(false);setPreview(false);setError('');setNotice('');if(next?.kind==='doc')setSelected(next.id);return true;}
  function open(id:string){const d=vault?.documents.find(d=>d.id===id);if(d&&choose(docDraft(d)))setTab('docs');}
  async function refresh(){setBusy(true);setError('');try{setVault(await api());setNotice('列表已刷新；正在编辑的草稿保持不变。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function mutate(action:Record<string,unknown>,message:string){setBusy(true);setError('');try{const v=await api(action);setVault(v);setNotice(message);return v;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
  async function save(){if(!draft)return;const fields={title:draft.title,content:draft.content,tags:draft.tags.split(/[,，]/).map(s=>s.trim()).filter(Boolean),enabled:draft.enabled,pinned:draft.pinned};const v=await mutate(draft.kind==='doc'?{action:'update',id:draft.id,revision:draft.revision,...fields}:draft.kind==='proposal'?{action:'approve',id:draft.id,...fields}:{action:'create',path:draft.path,...fields},draft.kind==='proposal'?'已确认记忆；启用后可用于后续任务。':'记忆已保存；启用的内容将在后续任务中生效。');if(v){const saved=draft.kind==='doc'?v.documents.find(d=>d.id===draft.id)!:v.documents.at(-1)!;const next=docDraft(saved);setBaseline(JSON.stringify(next));setDraft(next);setSelected(next.id);setTab('docs');}}
  async function remove(){if(!draft||!window.confirm(draft.kind==='proposal'?'忽略这条候选记忆？':'删除这篇记忆文档？其他文档中的引用将保留为未解析链接。'))return;const v=await mutate(draft.kind==='proposal'?{action:'reject',id:draft.id}:{action:'delete',id:draft.id,revision:draft.revision},'已移除。');if(v){setBaseline('');setDraft(null);setSelected('');}}
  function newDoc(){if(choose({kind:'new',id:'',revision:0,path:'',title:'',content:'',tags:'',enabled:true,pinned:false}))setTab('docs');}
  async function importFile(input:File){if(input.size>80000||!/\.md$/i.test(input.name)){setError('请选择不超过 20,000 字符的 .md 文档。');return;}try{const content=await input.text();if(content.length>20000)throw new Error('文档超过 20,000 字符，请拆分后导入。');if(choose({kind:'new',id:'',revision:0,path:input.name,title:input.name.replace(/\.md$/i,''),content,tags:'',enabled:true,pinned:false}))setTab('docs');}catch(e){setError((e as Error).message);}}
  const documents=vault?.documents||[];
  const relations=useMemo(()=>memoryLinks(vault?.documents||[]),[vault]);
  const filtered=useMemo(()=>rankMemories(vault?.documents||[],query).map(r=>r.doc).filter(d=>!tag||d.tags.includes(tag)).sort((a,b)=>Number(b.pinned)-Number(a.pinned)),[vault,query,tag]);
  const current=documents.find(d=>d.id===selected);
  const incoming=relations.links.filter(l=>l.target===(tab==='graph'?selected:draft?.id)).map(l=>documents.find(d=>d.id===l.source)!);
  const outgoing=relations.links.filter(l=>l.source===(tab==='graph'?selected:draft?.id)).map(l=>documents.find(d=>d.id===l.target)!);
  function change(patch:Partial<Draft>){setDraft(d=>d?{...d,...patch}:d);setNotice('');}
  return <dialog aria-label="记忆中心" className="modal memory-modal" ref={dialog} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===dialog.current)close();}}><div className="modal-top"><h2><Brain size={21}/> 记忆中心 <small>{identity.kind==='account'?identity.name:'访客'}的知识空间</small></h2><button className="icon-button" aria-label="关闭记忆中心" disabled={busy} onClick={close}><X size={20}/></button></div><div className="memory-center">
    <div className="memory-hero"><div><span className="memory-eyebrow">PERSONAL CONTEXT</span><h3>让每一次创造，更懂你。</h3><p>档案、偏好与经验，在你的项目之间延续。</p></div><div className="memory-global"><label><input type="checkbox" checked={vault?.enabled??false} disabled={!vault||busy} onChange={e=>void mutate({action:'settings',enabled:e.target.checked,revision:vault!.revision},'全局记忆设置已更新。')}/>跨项目记忆</label><small>{vault?.enabled?'已开启 · 新记忆先确认再使用':'已暂停 · 不再检索或新增候选'}</small></div></div>
    <div className="memory-tabs">{([{id:'docs',label:'文档索引',icon:BookOpen},{id:'graph',label:'关系图谱',icon:GitFork},{id:'pending',label:`待确认${vault?.proposals.length?' · '+vault.proposals.length:''}`,icon:Inbox},{id:'history',label:'使用记录',icon:History}] as const).map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><t.icon size={15}/>{t.label}</button>)}<button className="memory-refresh" aria-label="刷新记忆库" disabled={busy||loading} onClick={()=>void refresh()}><RefreshCw size={15} className={busy?'spin':''}/></button></div>
    {error&&<div className="memory-message failure" role="alert">{error}</div>}{notice&&<div className="memory-message" role="status">{notice}</div>}
    {loading?<div className="memory-empty"><Loader2 className="spin"/>正在读取你的记忆空间…</div>:!vault?<div className="memory-empty">暂时无法加载记忆库。<button onClick={()=>void refresh()}>重试</button></div>:<>
    {(tab==='docs'||tab==='pending')&&<div className="memory-body"><aside className="memory-library">
      {tab==='docs'?<><div className="memory-search"><Search size={14}/><input aria-label="搜索记忆文档" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、内容、标签"/></div><select aria-label="筛选记忆标签" value={tag} onChange={e=>setTag(e.target.value)}><option value="">全部标签 · {documents.length} 篇</option>{[...new Set(documents.flatMap(d=>d.tags))].sort().map(t=><option key={t} value={t}>#{t}</option>)}</select><div className="memory-library-actions"><button disabled={busy} onClick={newDoc}><Plus size={14}/>新建</button><button disabled={busy} onClick={()=>file.current?.click()}><Upload size={14}/>导入 .md</button><input ref={file} type="file" accept=".md,text/markdown" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='';}}/></div><button className={`memory-file index ${index?'active':''}`} onClick={()=>{if(choose(null))setIndex(true);}}><FileText size={16}/><span>INDEX.md<small>自动生成的全局文档索引</small></span></button><div className="memory-file-list">{filtered.map(d=><button disabled={busy} className={`memory-file ${draft?.id===d.id&&!index?'active':''}`} key={d.id} onClick={()=>choose(docDraft(d))}><FileText size={16}/><span>{d.title}<small>{d.path}</small></span><i title={d.enabled?(d.pinned?'常驻记忆':'按需检索'):'已暂停'} className={!d.enabled?'paused':d.pinned?'pinned':''}/></button>)}{!filtered.length&&<p className="memory-empty small">没有匹配的文档</p>}</div></>:<><div className="memory-library-note"><Inbox size={23}/><strong>先确认，再记住</strong><p>Agent 只能提交候选。你可以修改内容，再确认是否留作长期记忆。</p></div>{vault.proposals.map(p=><button disabled={busy} key={p.id} className={`memory-file ${draft?.id===p.id?'active':''}`} onClick={()=>choose(proposalDraft(p))}><Inbox size={15}/><span>{p.title}<small>{date(p.createdAt)}</small></span></button>)}{!vault.proposals.length&&<div className="memory-empty small">暂无待确认记忆<br/>可在对话中告诉 Agent“请记住我的偏好”。</div>}</>}
    </aside><main className="memory-editor-area">
      {index&&tab==='docs'?<><div className="memory-editor-top"><div><strong>INDEX.md</strong><small>自动索引 · 根据已保存文档实时生成</small></div><button className="secondary-button" onClick={()=>download('INDEX.md',markdownIndex(vault))}><Download size={14}/>导出</button></div><Markdown content={markdownIndex(vault)} documents={documents} open={open}/></>:draft&&(tab==='docs'?draft.kind!=='proposal':draft.kind==='proposal')?<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}>
      <div className="memory-editor-top"><div><strong>{draft.kind==='new'?'新建 Markdown 文档':draft.kind==='proposal'?'确认候选记忆':draft.path}</strong><small>{draft.kind==='doc'?`版本 ${draft.revision} · ${dirty?'有未保存的修改':'已保存'}`:'确认内容后保存到当前空间'}</small></div><button type="button" className="secondary-button" onClick={()=>setPreview(!preview)}>{preview?'编辑 Markdown':'阅读预览'}</button></div>
      {draft.kind==='proposal'&&<div className="memory-proposal-reason"><strong>提议依据</strong><p>{vault.proposals.find(p=>p.id===draft.id)?.reason}</p><small>来自 Agent · {date(vault.proposals.find(p=>p.id===draft.id)?.createdAt||0)}</small></div>}
      {draft.kind==='new'&&<label className="memory-label">文档路径<input required maxLength={140} value={draft.path} onChange={e=>change({path:e.target.value})} placeholder="例如 notes/设计偏好.md"/></label>}
      <label className="memory-label">标题<input required maxLength={80} value={draft.title} onChange={e=>change({title:e.target.value})} placeholder="为这篇记忆取一个名字"/></label>
      {preview?<Markdown content={draft.content} documents={documents} open={open}/>:<label className="memory-label memory-content-label">Markdown 内容<span className="memory-content-hint">使用 [[文档路径]] 连接知识 · {draft.content.length.toLocaleString()} / 20,000</span><textarea aria-label="Markdown 内容" maxLength={20000} value={draft.content} onChange={e=>change({content:e.target.value})} placeholder={draft.path==='USER.md'?'# 用户档案\n\n写下你希望 Agent 了解的背景、语言、设计风格与协作习惯。\n\n相关经验：[[MEMORY.md]]':'# 长期记忆\n\n写下值得跨项目复用的偏好或经验。用 [[USER.md]] 建立关联。'}/></label>}
      <label className="memory-label">标签<input value={draft.tags} maxLength={370} onChange={e=>change({tags:e.target.value})} placeholder="设计, 技术栈, 工作习惯（逗号分隔）"/></label><div className="memory-options"><label><input type="checkbox" checked={draft.enabled} onChange={e=>change({enabled:e.target.checked})}/>允许 Agent 使用</label><label><input type="checkbox" checked={draft.pinned} onChange={e=>change({pinned:e.target.checked})}/>常驻记忆</label><span>最多优先加载 4 篇常驻记忆，其他文档按任务检索</span></div>
      <div className="memory-editor-actions"><button className="primary-button" type="submit">{busy?<Loader2 className="spin" size={15}/>:<Check size={15}/>} {draft.kind==='proposal'?'确认并记住':'保存文档'}</button><button type="button" className="secondary-button" onClick={()=>download(draft.path.split('/').at(-1)||'memory.md',draft.content)}><Download size={14}/>导出 .md</button>{draft.kind==='doc'&&<button type="button" className="memory-text-button" onClick={()=>{const d=vault.documents.find(d=>d.id===draft.id);if(d)choose(docDraft(d));}}>重新载入文档</button>}{draft.kind!=='new'&&!['USER.md','MEMORY.md'].includes(draft.path)&&<button type="button" className="memory-delete" onClick={()=>void remove()}><Trash2 size={14}/>{draft.kind==='proposal'?'忽略':'删除'}</button>}</div>
      </fieldset></form>:<div className="memory-empty"><Brain size={32}/><strong>{tab==='pending'?'由你决定，什么值得留下':'选择一篇文档，开始整理你的记忆'}</strong><p>{tab==='pending'?'选择候选查看原文与提议依据。未经确认的内容不会用于任务。':'可以创建、导入 Markdown，或从 USER.md 写下你的偏好。'}</p></div>}
      {tab==='docs'&&draft?.kind==='doc'&&!index&&<div className="memory-relations"><strong>关联文档</strong><div><span>引用 →</span>{outgoing.map(d=><button type="button" key={d.id} onClick={()=>open(d.id)}>{d.title}</button>)}{!outgoing.length&&<small>暂无引用</small>}</div><div><span>反向链接 ←</span>{incoming.map(d=><button type="button" key={d.id} onClick={()=>open(d.id)}>{d.title}</button>)}{!incoming.length&&<small>暂无反向链接</small>}</div>{relations.unresolved.filter(l=>l.source===draft.id).length>0&&<p>未解析：{relations.unresolved.filter(l=>l.source===draft.id).map(l=>`[[${l.target}]]`).join('、')}</p>}</div>}
    </main></div>}
    {tab==='graph'&&<div className="memory-graph-layout"><MemoryGraph documents={documents} selected={selected} onSelect={setSelected}/><aside className="memory-graph-detail">{current?<><span className="memory-eyebrow">SELECTED NOTE</span><h3>{current.title}</h3><code>{current.path}</code><p>{current.content.slice(0,250)||'还没有内容，点击下方开始书写。'}</p><div className="memory-tags">{current.tags.map(t=><span key={t}>#{t}</span>)}</div><button className="primary-button" onClick={()=>open(current.id)}>打开文档</button><h4>反向链接 · {incoming.length}</h4>{incoming.map(d=><button key={d.id} className="memory-related" onClick={()=>setSelected(d.id)}>{d.title}</button>)}<h4>引用 · {outgoing.length}</h4>{outgoing.map(d=><button key={d.id} className="memory-related" onClick={()=>setSelected(d.id)}>{d.title}</button>)}</>:<p>点击节点，查看文档和它的关联。</p>}<small>仅展示明确的文档引用，不推断语义关系。暂停文档仍保留在图中。</small></aside></div>}
    {tab==='history'&&<div className="memory-history"><div className="memory-history-intro"><History size={25}/><div><h3>记忆是如何参与任务的</h3><p>这里记录任务启动时提供给 Agent 的文档节选，最多保留 20 次。不代表模型一定采纳，也不包含后续手动工具读取。</p></div></div>{vault.recalls.length?vault.recalls.map((r,i)=><article key={r.runId+String(r.at)+i}><time>{date(r.at)}</time><strong>{r.query||'未记录任务摘要'}</strong><div>{r.documents.length?r.documents.map(d=><button key={d.id} onClick={()=>open(d.id)} disabled={!documents.some(x=>x.id===d.id)}>{d.path}<small>v{d.revision}</small></button>):<span>没有加载记忆文档</span>}</div></article>):<div className="memory-empty"><History size={30}/><strong>还没有使用记录</strong><p>保存记忆后启动一次 Agent 任务，就能看到加载记录。</p></div>}</div>}
    <footer className="memory-footer"><span>{documents.length} 篇文档 · {vault.proposals.length} 条待确认</span><span>当前服务内跨项目持久化 · 暂停与删除从后续读取生效</span><button onClick={()=>download('atmos-memory-export.json',JSON.stringify({version:1,documents:vault.documents,proposals:vault.proposals},null,2),'application/json')}>导出记忆备份</button></footer></>}
  </div></dialog>;
}
