'use client';
import {useEffect,useState} from 'react';
import {Check,Loader2,ShieldCheck} from 'lucide-react';
import {trustLabels,type TrustMode,type TrustSettings} from '@/lib/trust-types';
export function TrustSettingsPanel({ownerId,onSaved}:{ownerId:string;onSaved?:(mode:TrustMode)=>void}){
 const [current,setCurrent]=useState<TrustSettings|null>(null),[mode,setMode]=useState<TrustMode>('important'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{const controller=new AbortController();void fetch('/api/security',{headers:{'X-Atmos-Owner':ownerId},signal:controller.signal}).then(async r=>{const d=await r.json() as TrustSettings&{error?:string};if(!r.ok)throw new Error(d.error||'无法读取信任设置');setCurrent(d);setMode(d.mode);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[ownerId]);
 async function save(){if(!current)return;setBusy(true);setError('');try{const response=await fetch('/api/security',{method:'POST',headers:{'Content-Type':'application/json','X-Atmos-Owner':ownerId},body:JSON.stringify({mode,revision:current.revision})}),data=await response.json() as TrustSettings&{error?:string};if(!response.ok)throw new Error(data.error||'保存失败');setCurrent(data);setNotice('信任设置已保存，从下一次任务生效。');onSaved?.(data.mode);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="trust-settings"><div className="trust-heading"><ShieldCheck size={25}/><p>决定 Agent 在执行工具前，何时需要征求你的意见。</p></div><fieldset disabled={!current||busy}>{(['always','important','allow'] as const).map(value=><label className={`trust-option ${mode===value?'selected':''}`} key={value}><input type="radio" name="trust-mode" value={value} checked={mode===value} onChange={()=>{setMode(value);setNotice('');}}/><span><strong>{trustLabels[value]}{value==='important'&&<small>默认</small>}</strong><p>{value==='always'?'每次工具调用都等待批准；回复中的高风险命令也会先检查。':value==='important'?'常规项目读写直接执行；删除、高风险命令和未知副作用工具需要批准。':'跳过工具和命令建议审批。已连接的插件可能操作本机文件或外部账户，请仅在你信任当前工具集时使用。'}</p></span></label>)}</fieldset><p className="trust-note">审批仅对该账户有效。一次批准只放行当前操作；拒绝、停止或过期后不会执行。账户隔离、路径限制及预览沙箱始终保留。已有待审批任务仍使用启动时的信任级别。</p>{error&&<p className="connection-result failure" role="alert">{error}</p>}{notice&&<p className="connection-result success" role="status">{notice}</p>}<button className="primary-button" disabled={!current||busy} onClick={()=>void save()}>{busy?<Loader2 className="spin" size={15}/>:<Check size={15}/>}保存信任设置</button></div>;
}
